<?php

namespace App\Docs;

use Illuminate\Http\Request;

interface MajorOccupationalAccident extends Info
{
    /**
     * @OA\Get(
     *     tags={"歷年重大職災資訊"},
     *     path="/api/major_occupational_accidents",
     *     summary="重大職災查詢",
     *     description="查詢全部或指定條件之重大職災資訊",
     *     @OA\Parameter(
     *         name="industryCode",
     *         in="query",
     *         description="指定行業別",
     *         required=false,
     *         @OA\Schema(type="string"),
     *         example="F"
     *     ),
     *     @OA\Parameter(
     *         name="accidentTypeCode",
     *         in="query",
     *         description="指定災害類型",
     *         required=false,
     *         @OA\Schema(type="string"),
     *         example="0004"
     *     ),
     *     @OA\Parameter(
     *         name="notifyingAgencyId",
     *         in="query",
     *         description="指定通報機關",
     *         required=false,
     *         @OA\Schema(type="integer"),
     *         example=9
     *     ),
     *     @OA\Parameter(
     *         name="startOccurrenceDate",
     *         in="query",
     *         description="開始發生日期",
     *         required=false,
     *         @OA\Schema(type="string"),
     *         example="2019-04-20"
     *     ),
     *     @OA\Parameter(
     *         name="endOccurrenceDate",
     *         in="query",
     *         description="結束發生日期",
     *         required=false,
     *         @OA\Schema(type="string"),
     *         example="2021-04-20"
     *     ),
     *     @OA\Parameter(
     *         name="page",
     *         in="query",
     *         description="頁碼",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         example=1 
     *     ),
     *     @OA\Parameter(
     *         name="count",
     *         in="query",
     *         description="每頁筆數",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         example=10 
     *     ),
     *     @OA\Response(
     *         response=200, 
     *         description="請求成功。",
     *         @OA\JsonContent(
     *             @OA\Property(
     *                 property="data",
     *                 type="array",
     *                 @OA\Items(
     *                     @OA\Property(
     *                         property="id",
     *                         type="integer"
     *                     ),
     *                     @OA\Property(
     *                         property="business_unit",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="detail_of_industry",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="occurrence_date",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="number_of_victims",
     *                         type="integer"
     *                     ),
     *                     @OA\Property(
     *                         property="project_name",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="accident_address",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="accident_location",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="business_owner",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="notifying_agency",
     *                         type="integer"
     *                     ),
     *                     @OA\Property(
     *                         property="industry",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="accident_type",
     *                         type="string"
     *                     ),
     *                 )
     *             ),
     *             @OA\Property(
     *                 property="statusCode",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="message",
     *                 type="string"
     *             ),
     *             @OA\Property(
     *                 property="countOfData",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="countOfPage",
     *                 type="integer"
     *             )
     *         )
     *     )
     * )
     */
    public function getMajorOccupationalAccidents(Request $request);

    /**
     * @OA\Get(
     *     tags={"歷年重大職災資訊"},
     *     path="/api/accident_type_statistics",
     *     summary="行業統計",
     *     description="統計單個行業別的所有災害類型",
     *     @OA\Parameter(
     *         name="industryCode",
     *         in="query",
     *         description="指定行業別",
     *         required=true,
     *         @OA\Schema(type="string"),
     *         example="F"
     *     ),
     *     @OA\Parameter(
     *         name="startOccurrenceDate",
     *         in="query",
     *         description="開始發生日期",
     *         required=false,
     *         @OA\Schema(type="string"),
     *         example="2019-04-20"
     *     ),
     *     @OA\Parameter(
     *         name="endOccurrenceDate",
     *         in="query",
     *         description="結束發生日期",
     *         required=false,
     *         @OA\Schema(type="string"),
     *         example="2021-04-20"
     *     ),
     *     @OA\Response(
     *         response=200, 
     *         description="請求成功。",
     *         @OA\JsonContent(
     *             @OA\Property(
     *                 property="data",
     *                 type="array",
     *                 @OA\Items(
     *                     @OA\Property(
     *                         property="accident_type",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="count_of_accident_type",
     *                         type="integer"
     *                     ),
     *                 )
     *             ),
     *             @OA\Property(
     *                 property="statusCode",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="message",
     *                 type="string"
     *             ),
     *             @OA\Property(
     *                 property="countOfData",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="countOfPage",
     *                 type="integer"
     *             )
     *         )
     *     )
     * )
     */
    public function getAccidentTypeStatistics(Request $request);

    /**
     * @OA\Get(
     *     tags={"歷年重大職災資訊"},
     *     path="/api/industry_statistics",
     *     summary="災害類型統計",
     *     description="統計單個災害類型的所有行業別",
     *     @OA\Parameter(
     *         name="accidentTypeCode",
     *         in="query",
     *         description="指定災害類型",
     *         required=true,
     *         @OA\Schema(type="string"),
     *         example="0001"
     *     ),
     *     @OA\Parameter(
     *         name="startOccurrenceDate",
     *         in="query",
     *         description="開始發生日期",
     *         required=false,
     *         @OA\Schema(type="string"),
     *         example="2019-04-20"
     *     ),
     *     @OA\Parameter(
     *         name="endOccurrenceDate",
     *         in="query",
     *         description="結束發生日期",
     *         required=false,
     *         @OA\Schema(type="string"),
     *         example="2021-04-20"
     *     ),
     *     @OA\Response(
     *         response=200, 
     *         description="請求成功。",
     *         @OA\JsonContent(
     *             @OA\Property(
     *                 property="data",
     *                 type="array",
     *                 @OA\Items(
     *                     @OA\Property(
     *                         property="industry",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="count_of_industry",
     *                         type="integer"
     *                     ),
     *                 )
     *             ),
     *             @OA\Property(
     *                 property="statusCode",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="message",
     *                 type="string"
     *             ),
     *             @OA\Property(
     *                 property="countOfData",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="countOfPage",
     *                 type="integer"
     *             )
     *         )
     *     )
     * )
     */
    public function getIndustryStatistics(Request $request);
}
