<?php

namespace App\Docs;

use Illuminate\Http\Request;

interface NotifyingAgency extends Info
{
    /**
     * @OA\Get(
     *     tags={"通報機關地圖"},
     *     path="/api/notifying_agencies/{id}",
     *     summary="通報機關",
     *     description="查詢單筆或多筆的通報機關。",
     *     @OA\Parameter(
     *          name="id",
     *          description="若想要查詢單筆，請帶入機關編碼，查多筆可不帶，這裡是因為Swagger不帶值會預設給空白。",
     *          required=false,
     *          in="path",
     *          @OA\Schema(
     *              type="integer",
     *              default=0 
     *          )
     *     ),
     *     @OA\Parameter(
     *         name="page",
     *         in="query",
     *         description="頁碼",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         example=1 
     *     ),
     *     @OA\Parameter(
     *         name="count",
     *         in="query",
     *         description="每頁筆數",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         example=10 
     *     ),
     *     @OA\Response(
     *         response=200, 
     *         description="請求成功。",
     *         @OA\JsonContent(
     *             @OA\Property(
     *                 property="data",
     *                 type="array",
     *                 @OA\Items(
     *                     @OA\Property(
     *                         property="id",
     *                         type="integer"
     *                     ),
     *                     @OA\Property(
     *                         property="agency_name",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="address",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="notified_hotline_at_work",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="notified_hotline_off_work",
     *                         type="string"
     *                     )
     *                 )
     *             ),
     *             @OA\Property(
     *                 property="statusCode",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="message",
     *                 type="string"
     *             ),
     *             @OA\Property(
     *                 property="countOfData",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="countOfPage",
     *                 type="integer"
     *             )
     *         )
     *     )
     * )
     */
    public function getNotifyingAgencies(Request $request, int $id = 0);

    /**
     * @OA\Get(
     *     tags={"通報機關地圖"},
     *     path="/api/jurisdiction_regions",
     *     summary="管轄區",
     *     description="查詢所有管轄區",
     *     @OA\Parameter(
     *         name="page",
     *         in="query",
     *         description="頁碼",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         example=1  
     *     ),
     *     @OA\Parameter(
     *         name="count",
     *         in="query",
     *         description="每頁筆數",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         example=10 
     *     ),
     *     @OA\Response(
     *         response=200, 
     *         description="請求成功。",
     *         @OA\JsonContent(
     *             @OA\Property(
     *                 property="data",
     *                 type="array",
     *                 @OA\Items(
     *                     @OA\Property(
     *                         property="id",
     *                         type="integer"
     *                     ),
     *                     @OA\Property(
     *                         property="region",
     *                         type="string"
     *                     )
     *                 )
     *             ),
     *             @OA\Property(
     *                 property="statusCode",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="message",
     *                 type="string"
     *             ),
     *             @OA\Property(
     *                 property="countOfData",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="countOfPage",
     *                 type="integer"
     *             )
     *         )
     *     )
     * )
     */
    public function getJurisdictionRegions(Request $request, int $na_id);

    /**
     * @OA\Get(
     *     tags={"通報機關地圖"},
     *     path="/api/jurisdiction_regions/{jr_id}/notifying_agencies",
     *     summary="指定管轄區之通報機關",
     *     description="利用管轄區查詢通報機關",
     *     @OA\Parameter(
     *          name="jr_id",
     *          description="帶入管轄區的id",
     *          required=true,
     *          in="path",
     *          @OA\Schema(
     *              type="integer",
     *              default=1 
     *          )
     *     ),
     *     @OA\Parameter(
     *         name="page",
     *         in="query",
     *         description="頁碼",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         example=1  
     *     ),
     *     @OA\Parameter(
     *         name="count",
     *         in="query",
     *         description="每頁筆數",
     *         required=true,
     *         @OA\Schema(type="integer"),
     *         example=10 
     *     ),
     *     @OA\Response(
     *         response=200, 
     *         description="請求成功。",
     *         @OA\JsonContent(
     *             @OA\Property(
     *                 property="data",
     *                 type="array",
     *                 @OA\Items(
     *                     @OA\Property(
     *                         property="id",
     *                         type="integer"
     *                     ),
     *                     @OA\Property(
     *                         property="agency_name",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="address",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="notified_hotline_at_work",
     *                         type="string"
     *                     ),
     *                     @OA\Property(
     *                         property="notified_hotline_off_work",
     *                         type="string"
     *                     )
     *                 )
     *             ),
     *             @OA\Property(
     *                 property="statusCode",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="message",
     *                 type="string"
     *             ),
     *             @OA\Property(
     *                 property="countOfData",
     *                 type="integer"
     *             ),
     *             @OA\Property(
     *                 property="countOfPage",
     *                 type="integer"
     *             )
     *         )
     *     )
     * )
     */
    public function getNotifyingAgenciesByJrId(Request $request, int $jr_id);
}
