cd notifying
python3 main.py
cd ../notifying_agencies
python3 main.py
cd ../counties_and_towns
python3 main.py
cd ../industrys
python3 main.py
cd ../accident_types
python3 main.py
cd ../major_occupational_accidents
python3 main.py